<a href="https://colab.research.google.com/github/Fintecuriosity11/Pytorch_Tutorial01/blob/master/PytorchTutorial_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![대체 텍스트](https://pytorch.org/tutorials/_images/pytorch-logo-flat.png)
# Import Pytorch  

In [0]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, **uninitialized:** 
초기화 돼지 않은 행렬 (5 * 3)  생성

An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.

초기화되지 않은 행렬이 선언되었지만, 사용하기 전에는 명확히 알려진 값을 포함하고 있지는 않습니다. 초기화되지 않은 행렬이 생성되면 그 시점에 할당된 메모리에 존재하던 값들이 초기값으로 나타납니다.

In [0]:
x = torch.empty(5, 3)
print(x)


tensor([[1.5934e-35, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])


Construct a randomly **initialized** matrix: 임의로 초기화 된 행렬 생성



In [0]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0889, 0.7903, 0.3336],
        [0.4673, 0.7828, 0.6152],
        [0.3602, 0.8705, 0.9681],
        [0.2764, 0.9806, 0.2126],
        [0.4674, 0.8748, 0.1481]])


Construct a matrix **filled zeros** and of **dtype long**: 데이터 타입이 long인 5*3 행렬 0으로 채움     

long (정수형) 8 byte



In [0]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor **directly** from data: 데이터로부터 tensor 직접 생성



In [0]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user.

또는 존재하는 tensor를 바탕으로 tensor를 만듭니다. 이 메소드(method)들은 사용자로부터 제공된 새로운 값이 없는 한, 입력 tensor의 속성들(예. dtype)을 재사용합니다.

In [0]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes    # new_* 메소드는 크기를 받습니다
print(x)                                      

x = torch.randn_like(x, dtype=torch.float)    # override dtype!                # dtype을 오버라이드(Override) 합니다!
print(x)                                      # result has the same size       # 결과는 동일한 크기를 갖습니다

                                              
                                             

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.5815,  0.3559,  0.2511],
        [ 1.0914,  0.9270,  0.9231],
        [-0.0882,  1.4813, -0.9666],
        [ 0.3309,  0.5235,  1.1679],
        [ 0.8769,  0.8438,  0.8069]])


Get its size: 행렬의 크기를 구하는 법

In [0]:
print(x.size())

torch.Size([5, 3])


# Operations (연산)

Addition: syntax 1 = 덧셈 문법 1

In [0]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.0794,  0.7467,  1.1399],
        [ 1.8997,  1.2924,  1.2541],
        [ 0.2994,  2.0264, -0.1703],
        [ 0.9545,  0.5755,  1.5057],
        [ 0.8999,  1.7795,  1.7312]])


Addition: syntax 2 = 덧셈 문법 2

In [0]:
print(torch.add(x, y))

tensor([[ 1.0794,  0.7467,  1.1399],
        [ 1.8997,  1.2924,  1.2541],
        [ 0.2994,  2.0264, -0.1703],
        [ 0.9545,  0.5755,  1.5057],
        [ 0.8999,  1.7795,  1.7312]])


Addition: providing an output tensor as argument = 덧셈: 결과 tensor를 인자로 제공

In [0]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.0794,  0.7467,  1.1399],
        [ 1.8997,  1.2924,  1.2541],
        [ 0.2994,  2.0264, -0.1703],
        [ 0.9545,  0.5755,  1.5057],
        [ 0.8999,  1.7795,  1.7312]])


Addition: in-place / 덧셈: 바꿔치기(In-place) 방식

* Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.


* 바꿔치기(In-place) 방식으로 tensor의 값을 변경하는 연산은 _ 를 접미사로 갖습니다. 예: x.copy_(y), x.t_() 는 x 를 변경합니다.



In [0]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.0794,  0.7467,  1.1399],
        [ 1.8997,  1.2924,  1.2541],
        [ 0.2994,  2.0264, -0.1703],
        [ 0.9545,  0.5755,  1.5057],
        [ 0.8999,  1.7795,  1.7312]])


* You can use standard NumPy-like indexing with all bells and whistles!

* NumPy스러운 인덱싱 표기 방법을 사용할 수도 있음

In [0]:
print(x[:, 1])

tensor([0.3559, 0.9270, 1.4813, 0.5235, 0.8438])


Resizing: If you want to resize/reshape tensor, you can use torch.view: / 

In [0]:
x = torch.randn(4, 4)
y = x.view(16)     #torch.view 함수로 텐서의 모양 변경  
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use .item() to get the value as a Python number / 만약 tensor에 하나의 값만 존재한다면, .item() 을 사용하면 숫자 값을 얻을 수 있습니다.

In [0]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3802])
-0.38017404079437256


#NumPy Bridge (변환)

* Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

* The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.


* Torch Tensor를 NumPy 배열(array)로 변환하거나, 그 반대로 하는 것은 매우 쉽습니다.

* (CPU 상의) Torch Tensor와 NumPy 배열은 저장 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

Converting a Torch Tensor to a NumPy Array / Torch Tensor를 NumPy 배열로 변환하기

In [0]:
a = torch.ones(5)        #torch.one= 
print(a)

tensor([1., 1., 1., 1., 1.])


2nd Example

In [0]:
b = a.numpy()
print(b)


[1. 1. 1. 1. 1.]


See how the numpy array changed in value. / NumPy 배열의 값이 어떻게 변하는지 확인

In [0]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


# Converting NumPy Array to Torch Tensor / NumPy 배열을 Torch Tensor로 변환하기

In [0]:
import numpy as np         # NumPy import해오는 과정
a = np.ones(5)             # np.one 
b = torch.from_numpy(a)    # Numpy Array -> Torch Tensor
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
